### ISSUE TITLE
インポートしたモデルの表情がNeutralにならない

### ISSUE THREAD

**Issue by kazekawa** [dmm-com/vrlab-dvrsdk#2]
どのVRサンプルでもインポートされたモデルの表情がneutralにならなかったため、調査をしました。

<hr>

[FaceController.cs](https://github.com/dmm-com/vrlab-dvrsdk/blob/main/DVRSDK/Assets/DVRSDK/DVRAvatar/Scripts/FaceController.cs) におきまして

### モデルインポート時
https://github.com/dmm-com/vrlab-dvrsdk/blob/cfb51cecf713692eab78d2a45b308b0cf9af3e8b/DVRSDK/Assets/DVRSDK/DVRAvatar/Scripts/FaceController.cs#L105
https://github.com/dmm-com/vrlab-dvrsdk/blob/cfb51cecf713692eab78d2a45b308b0cf9af3e8b/DVRSDK/Assets/DVRSDK/DVRAvatar/Scripts/FaceController.cs#L315
https://github.com/dmm-com/vrlab-dvrsdk/blob/cfb51cecf713692eab78d2a45b308b0cf9af3e8b/DVRSDK/Assets/DVRSDK/DVRAvatar/Scripts/FaceController.cs#L338
ここで表情はNeutralになるのですが、

<hr>

### Startの処理
https://github.com/dmm-com/vrlab-dvrsdk/blob/cfb51cecf713692eab78d2a45b308b0cf9af3e8b/DVRSDK/Assets/DVRSDK/DVRAvatar/Scripts/FaceController.cs#L112-L122

インポート後にStartが実行されるためBlendShapeがすべて0に戻されてしまい、
結局表情がneutralになっていないようです。

<hr>

解決案としてStartでSetFaceNeutralをコールすることを提案いたします。
```
private void Start()
{
    SetFaceNeutral();
    CreateAnimation();
}
```

ご検討よろしくお願いいたします。

**Comment by sh-akira** [comment]
ご報告ありがとうございました。次のリリースで修正されます
